# Generated by Django 4.1 on 2022-12-17 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_en',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_per',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_per',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='css_code_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='css_code_per',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='css_links_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='css_links_per',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_per',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='html_code_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='html_code_per',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='javascript_code_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='javascript_code_per',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='js_links_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='js_links_per',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language_type_en',
            field=models.CharField(choices=[('p', 'python'), ('d', 'django'), ('c', 'css'), ('h', 'html'), ('b', 'bootstrap'), ('j', 'javascript')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language_type_per',
            field=models.CharField(choices=[('p', 'python'), ('d', 'django'), ('c', 'css'), ('h', 'html'), ('b', 'bootstrap'), ('j', 'javascript')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id_en',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id_per',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publish_en',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publish_per',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_per',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='statuc_en',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'publish')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='statuc_per',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'publish')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_en',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_per',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_per',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_per',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
