# Generated by Django 4.1 on 2022-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_en_project_project_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Project_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Project_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='css_code_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='css_code_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='css_links_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='css_links_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='html_code_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='html_code_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='javascript_code_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='javascript_code_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='js_links_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='js_links_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language_type_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language_type_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publish_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publish_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statuc_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statuc_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_per',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_per',
        ),
        migrations.AlterField(
            model_name='project',
            name='css_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='css_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='html_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='js_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
