# Generated by Django 4.1 on 2022-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_project_en_remove_project_project_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_por',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_por',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
