# Generated by Django 4.1 on 2022-12-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_description_por_project_title_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_por',
            new_name='description_pt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_por',
            new_name='title_pt',
        ),
    ]
