# Generated by Django 4.1 on 2022-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_description_por_project_description_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
