# Generated by Django 4.1 on 2022-12-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_description_de_project_title_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='css_links',
        ),
        migrations.RemoveField(
            model_name='project',
            name='js_links',
        ),
    ]
