# Generated by Django 4.1 on 2022-12-21 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_css_links_remove_project_js_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Project', models.FileField(blank=True, null=True, upload_to='projects')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'publish')], max_length=1)),
            ],
        ),
    ]
