# Generated by Django 4.1 on 2022-12-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_project_id_djangoprojects_is_private_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoProjects',
        ),
    ]
