# Generated by Django 4.1 on 2022-12-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_my_self_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_my_self_per',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='job_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='job_per',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_per',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='pictuer_en',
            field=models.ImageField(null=True, upload_to='my_pictuer'),
        ),
        migrations.AddField(
            model_name='about',
            name='pictuer_per',
            field=models.ImageField(null=True, upload_to='my_pictuer'),
        ),
    ]
