# Generated by Django 4.1 on 2022-12-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_about_my_self_en_about_about_my_self_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='pictuer_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='pictuer_per',
        ),
    ]
