# Generated by Django 4.1 on 2022-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_about_pictuer_en_remove_about_pictuer_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_my_self_por',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='job_por',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_por',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
