# Generated by Django 4.1 on 2022-12-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_about_my_self_por_about_job_por_about_name_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_my_self_por',
            new_name='about_my_self_pt',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='job_por',
            new_name='job_pt',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name_por',
            new_name='name_pt',
        ),
    ]
