# Generated by Django 4.1 on 2022-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_about_my_self_por_about_about_my_self_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_my_self_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='job_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
