# Generated by Django 4.1 on 2022-12-17 22:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_per',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_en',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_per',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='my_id_en',
            field=models.IntegerField(help_text='to show the model in the page please take the my_id to 1', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='my_id_per',
            field=models.IntegerField(help_text='to show the model in the page please take the my_id to 1', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_en',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_per',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
