# Generated by Django 4.1 on 2022-12-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_address_en_contact_address_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_per',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='my_id_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='my_id_per',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number_per',
        ),
    ]
