# Generated by Django 4.1 on 2022-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_contact_email_en_remove_contact_email_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_por',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
