# Generated by Django 4.1 on 2022-12-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contact_address_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address_por',
            new_name='address_pt',
        ),
    ]
