# Generated by Django 4.1 on 2022-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_address_por_contact_address_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_de',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
