# Generated by Django 4.1 on 2022-12-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='learn_presentage_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='learn_presentage_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_per',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
