# Generated by Django 4.1 on 2022-12-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_learn_presentage_en_skill_learn_presentage_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='learn_presentage_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='learn_presentage_per',
        ),
    ]
