# Generated by Django 4.1 on 2022-12-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_title_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title_por',
            new_name='title_pt',
        ),
    ]
