# Generated by Django 4.1 on 2022-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_rename_title_por_skill_title_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
